Repository projectsyn/modulesync-control, pull requests merged in 2021-11, with the labels that each got.

#28 Remove nonsensical comment referencing Makefiles
  moduleroot/.editorconfig.erb
Labels: bug

#46 Onboard component openshift4-registry
  managed_modules.yml
Labels: ignore

#49 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  moduleroot/.github/PULL_REQUEST_TEMPLATE.md.erb
Labels: change

#50 Clean compiled artifacts before generating golden files
  moduleroot/Makefile.erb
Labels: change

#51 Disable Renovate dashboard
  moduleroot/renovate.json.erb
Labels: change
