Repository projectsyn/modulesync-control, pull requests merged in 2022-03, with the labels that each got.

#63 Update Antora preview image to 3.0.1.1
  moduleroot/Makefile.vars.mk.erb
Labels: change

#62 Add logic to generate Renovate `postUpgradeTasks`
  config_defaults.yml
  moduleroot/.github/workflows/test.yaml.erb
  moduleroot/Makefile.erb
  moduleroot/Makefile.vars.mk.erb
  moduleroot/renovate.json.erb
Labels: enhancement

#64 Explicitly set `GITHUB_BASE_URL` for modulesync
  .github/workflows/sync.yml
Labels: bug

#65 Update `actions/checkout` to v3 in component template
  moduleroot/.github/workflows/release.yaml.erb
  moduleroot/.github/workflows/test.yaml.erb
Labels: dependency

#66 Update GitHub actions `setup-go` and `cache` to v3 in template
  moduleroot/.github/workflows/test.yaml.erb
Labels: dependency

#67 Remove support for old `matrix` parameter in GitHub actions template
  config_defaults.yml
  moduleroot/.github/workflows/test.yaml.erb
Labels: change

#68 Support Podman out of the box
  moduleroot/Makefile.vars.mk.erb
Labels: change

#69 Split `COMMODORE_CMD` and `COMPILE_CMD`
  moduleroot/Makefile.erb
  moduleroot/Makefile.vars.mk.erb
Labels: enhancement
